name: e2e

on:
  push:
    branches:
      - "main"
      - "release-[0-9]+.[0-9]"
  pull_request:
    branches: "**"

concurrency:
  group: e2e-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  e2e:
    name: e2e
    uses: ./.github/workflows/e2e-lane.yml

    permissions:
      contents: read
      packages: write
      actions: read

    with:
      race: false

  e2e-race:
    name: e2e (race)
    uses: ./.github/workflows/e2e-lane.yml

    permissions:
      contents: read
      packages: write
      actions: read

    with:
      race: true
